# Generated by Django 2.2.6 on 2019-10-15 08:23

import apps.holy_place.helper.file_helper
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rate_count', models.IntegerField()),
                ('thumbnail_image', models.ImageField(upload_to=apps.holy_place.helper.file_helper.PathAndRename('media/place_thumbnail_image/'))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holy_place.Category')),
            ],
        ),
    ]
