# Generated by Django 2.2.6 on 2019-10-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_home',
            field=models.BooleanField(default=True),
        ),
    ]
