# Generated by Django 2.2.6 on 2019-10-15 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holy_place', '0002_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='thumbnail_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
