# Generated by Django 2.2.6 on 2019-10-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_place', '0002_category_show_in_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
